#!/bin/sh

# Change `style.css` or `style.min.css` to whatever you would like your compiled
# stylesheet to be called. Do not rename `style.scss` or alter references to it.

# No minification
sass --watch global.scss:../css/global.css --style expanded

# Minification
sass --watch global.scss:../css/global.min.css --style compressed

exit 0
